version: '3.8'

services:
  account-service:
    build: ./account-service
    ports:
      - "8080:8080"
    environment:
      - SUPABASE_URL=<your_supabase_url>
      - SUPABASE_KEY=<your_supabase_key>

  payment-service:
    build: ./payment-service
    ports:
      - "8081:8081"
    environment:
      - SUPABASE_URL=<your_supabase_url>
      - SUPABASE_KEY=<your_supabase_key>

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - account-service
      - payment-service
